apiVersion: v1
kind: Service
metadata:
  name: visualizer
spec:
  selector:
    app: visualizer
  ports:
    - port: 5173
      targetPort: 5173
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualizer
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
      - name: visualizer
        image: navora/visualizer:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_COORDINATOR_ADDR
          value: "http://coordinator:50051"

